# Verwende ein Python-Image
FROM python:3.9-slim

# Arbeitsverzeichnis festlegen
WORKDIR /app

# Abhängigkeiten installieren
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Skript kopieren
# COPY wait_for_postgres.sh .
COPY data_migration/migrate.py data_migration/migrate.py
COPY data_read/read.py data_read/read.py
COPY data_update/update.py data_update/update.py
COPY data_delete/delete.py data_delete/delete.py
COPY db_connection.py db_connection.py

# Mache das Skript ausführbar
# RUN chmod +x wait_for_postgres.sh

# Setze den Einstiegspunkt auf das Warte-Skript und das Haupt-Skript
# ENTRYPOINT ["./wait_for_postgres.sh"]
# Führen Sie alle Skripte nacheinander aus
CMD ["sh", "-c", "python data_migration/migrate.py && python data_read/read.py && python data_update/update.py && python data_delete/delete.py"]



